baseurl = "/"
languageCode = "de"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme = "terminal"
paginate = 5
defaultContentLanguage = "de"

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = true # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  TocTitle = "Inhalt" # default


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.de]
    languageName = "Deutsch"
    title = "TechWiccan Blog"

    [languages.de.params]
      subtitle = "Eine Reise durch Software-Entwicklung und nordische Mythologie"
      owner = "Marvin"
      keywords = ""
      copyright = ""
      menuMore = "Mehr anzeigen"
      readMore = "Mehr lesen"
      readOtherPosts = "Weitere Einträge lesen"
      newerPosts = "Neuere Einträge"
      olderPosts = "Ältere Einträge"
      missingContentMessage = "Seite nicht gefunden..."
      missingBackButtonLabel = "Zurück zur Startseite"
      minuteReadingTime = "Minuten gelesen"
      words = "Wörter"

      [languages.de.params.logo]
        logoText = "TechWiccan Blog"
        logoHomeLink = "/"

      [languages.de.menu]
        [[languages.de.menu.main]]
          identifier = "about"
          name = "Über mich"
          url = "/about"
        [[languages.de.menu.main]]
          identifier = "showcase"
          name = "Showcase"
          url = "/showcase"